name: Build Android

on:
  workflow_dispatch:
jobs:
  download-models:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download tiny ggml model
        run: |
          git submodule update --init
          ./download-vad-model.sh
          mkdir models
          mv ggml-silero-v5.1.2.bin models/
      - uses: actions/upload-artifact@v4
        with:
          name: test-models
          path: models/*.bin
          retention-days: 2

  build_android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r25c
          add-to-path: true
          local-cache: true
      - name: Make build_android.sh executable
        run: chmod +x ./build_android.sh
      - name: Build Android JAR
        run: |
          if test -e "src/main/native/whisper/examples/grammar-parser.cpp"; then echo "grammar-parser.cpp found"; else echo "grammar-parser.cpp not found"; fi
          ./build_android.sh
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-jar
          path: |
            whisperjni-build/*.jar
